version: '3.9'

services:

  random_dog_service:
    restart: on-failure
    container_name: car_api_service
    build: car_api_service/
    ports:
      - "8001:80"

  korgi_shop_service:
    restart: on-failure
    container_name: auto_shop_service
    build: auto_shop_service/
    ports:
      - "8000:80"
